### ISSUE TITLE
i use the same properties, its all fine at incubator version, but start application fail at graduation version

### ISSUE THREAD

**Issue by msgcode** [alibaba/spring-cloud-alibaba#1142]
#### Which Component
```
spring-cloud-starter-alibaba-nacos-discovery
spring-cloud-starter-alibaba-nacos-config
```

#### Describe the bug
i use the same properties, its all fine at incubator version, but start application fail at graduation version

#### To Reproduce
none

#### Expected behavior
start application normally

#### Screenshots
![image](https://user-images.githubusercontent.com/8230132/71334775-840e7800-257a-11ea-827c-d9225584da14.png)

#### Additional context
```  properties config
spring:
  cloud:
    nacos:
      config:
        server-addr: xxx.com:8848
      discovery:
        server-addr: xxx.com:8848
```
#### dependency version
```
  spring-boot: 1.5.9.RELEASE
  spring-cloud: Edgware.RELEASE
  alibaba-cloud: 1.5.1.RELEASE
```

i dont need to use 'endpoin' now, is it optional?

**Comment by echooymxq** [comment]
you can set a breakpoint to debug it, the  error usually happens when the serverAddr not set correctly [NacosConfigProperties](https://github.com/alibaba/spring-cloud-alibaba/blob/ef1d3083eccf78f946a698cd3040620ec07b8f89/spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java#L368). In addition,since the Spring Cloud Edgware cease maintenance. I suggest that you upgrade to a higher version, see [Spring Cloud Edgware EOL](https://github.com/alibaba/spring-cloud-alibaba/issues/974).
