### ISSUE TITLE
    com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createProducerMessageHandler(RocketMQMessageChannelBinder.java:172)

### ISSUE THREAD

**Issue by new1943** [alibaba/spring-cloud-alibaba#1615]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Rocketmq

**Describe the bug**
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createProducerMessageHandler(RocketMQMessageChannelBinder.java:172)

The following method did not exist:

    'java.util.List org.springframework.integration.channel.AbstractMessageChannel.getChannelInterceptors()'

**To Reproduce**
```
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR6</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2.2.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
        </dependency>

```

**Expected behavior**
Start Fail

**Screenshots**
![image](https://user-images.githubusercontent.com/9349166/89180594-a6fb1300-d5c4-11ea-8f05-4f5e60573d01.png)
![image](https://user-images.githubusercontent.com/9349166/89180687-da3da200-d5c4-11ea-8395-ee4a3794d4b9.png)

**Additional context**

**Comment by zuryazen** [comment]
I agree




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 晚上8:08
收件人:&nbsp;"alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[alibaba/spring-cloud-alibaba]     com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createProducerMessageHandler(RocketMQMessageChannelBinder.java:172) (#1615)





 
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
 We recommend using English. If you are non-native English speaker, you can use the translation software.
 
Which Component
 Rocketmq
 
Describe the bug
 
 
APPLICATION FAILED TO START
 
 
Description:
 
An attempt was made to call a method that does not exist. The attempt was made from the following location:
 com.alibaba.cloud.stream.binder.rocketmq.RocketMQMessageChannelBinder.createProducerMessageHandler(RocketMQMessageChannelBinder.java:172)  
The following method did not exist:
 'java.util.List org.springframework.integration.channel.AbstractMessageChannel.getChannelInterceptors()'  
To Reproduce
 Steps to reproduce the behavior:
 
 org.springframework.cloud
 spring-cloud-dependencies
 Hoxton.SR6
 pom
 import
 
                 org.springframework.cloud                 spring-cloud-dependencies                 2.2.0.RELEASE                 pom                 import                  <dependency&gt;         <groupId&gt;com.alibaba.cloud</groupId&gt;         <artifactId&gt;spring-cloud-starter-stream-rocketmq</artifactId&gt;     </dependency&gt;  
Expected behavior
 Start Fail
 
Screenshots
 
 
 
Additional context

**Comment by new1943** [comment]
problem may be fixed . see https://github.com/alibaba/spring-cloud-alibaba/pull/1503#issue-426547463
