### ISSUE TITLE
rocketmq顺序消费异常时，能否进入死信队列，还是只能配置suspendCurrentQueueTimeMillis？

### ISSUE THREAD

**Issue by 1078699311** [alibaba/spring-cloud-alibaba#1847]
1、配置spring.cloud.stream.rocketmq.bindings.<inputName>.orderly=true
2、顺序消费异常时，RocketMQConsumerProperties默认suspendCurrentQueueTimeMillis=1000
请问顺序消费异常该如何关闭重复消费？

**Comment by zkzlx** [comment]
I don't quite catch what you mean.
The design idea of `RocketMQ` orderly consumer :  the next message cannot proceed until the current message has been successfully used, otherwise it will be suspended with `SUSPEND_CURRENT_QUEUE_A_MOMENT` to suspend other consumers of the queue until the original message is repeatedly and successfully retried.

**Comment by zkzlx** [comment]
you can use the beta version #2029 ,see if it meets your needs.
