### ISSUE TITLE
how to share default service

### ISSUE THREAD

**Issue by star110** [alibaba/spring-cloud-alibaba#2018]
**Which Component**
Nacos Discovery

I want to register a default group service  and share with other group service.  If no this feature, each of us need to start up too many IDE and service, but I just need to care for my code.

**Comment by theonefx** [comment]
Can you give me an example? I'm not quite sure what your question is.

**Comment by star110** [comment]
&nbsp;As you know, every programmer just develop one or some of micro service. when I try to debug my code,
&nbsp;I use myself discovery group. how can i just start up my service and use others public service?&nbsp;
&nbsp;we are not in one discovery group and I don't&nbsp;want start up all of the micro&nbsp;service.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/spring-cloud-alibaba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] how to share default service (#2018)





 
Can you give me an example? I'm not quite sure what your question is.

**Comment by yuhuangbin** [comment]
Different grouping calls are not supported. If you want local debugging, you can try registering the local service with the same namespace and dropping the old service offline.

**Comment by beanww** [comment]
First, I would like to inquire about the usage scenarios of groups. If a service is assigned to a group, and both its callers and callees must belong to the same group, what is the difference between this and the isolation effect of ”namespaces“?

Second, I believe the requirement of this issue is necessary. Consider a scenario in a microservice cluster where the orderService needs to serve both crmService and mallService. To ensure the stability of crmService and mallService as much as possible, orderService can be deployed to two separate groups: "crm" and "mall". In this way, crmService only invokes the orderService in the "crm" group, so that if an exception occurs in the "crm"-grouped orderService, it will not affect the "mall"-grouped orderService. This means that services can achieve isolation through groups—specifically, after a service is assigned to a group, its callers can invoke it by specifying the group, while the callee should preferably avoid external calls (i.e., such group-assigned services should  not make outward calls; otherwise, this requirement will spread to the entire microservice cluster, forcing all services to use this group).

首先我想咨询一下，group的使用场景是什么？如果服务设置group后，其调用者、被调用者也必须是同一个group，那么跟namespace的隔离效果有什么区别呢？
其次，本issue的诉求我想是需要的，考虑一个场景，一个微服务集群中，orderService服务既要给crmService使用，又要给mallService使用，为了让crm、mall能够尽量稳定，orderService可以分别发布到crm和mall两个group上，这样crm只调用crm分组的orderService，从而使得crm分组的orderService异常时，不会影响到mall分组的orderService，相当于服务可以通过group达到隔离的效果，即服务设置group后，其调用者可以通过指定group的方式调用，其被调用者尽量没有（即此类group的服务尽量不要再往外调用，否则会传染到整个服务集群都得用这个group了）
