### ISSUE TITLE
关于nacos的使用场景

### ISSUE THREAD

**Issue by l42111996** [alibaba/spring-cloud-alibaba#2638]
**Which Component**
Nacos Discovery

**Is your feature request related to a problem? Please describe.**
我们在使用服务发现的时候有一种需求，有一群tcp服务器(A)注册到nacos，有一个管理服务器会根据一些需求(用户最少)选定一台给客户端去连接，所以需要定时去推送tcp服务器在线用户状态，我开始想用metadata里面去存用户数量，发现metadata不能更新，然后我就通过redis去另外存了一份服务器用户数量数据，感觉等于有了两个服务发现

**Describe the solution you'd like**
对于这种场景有更好的解决方案吗？

**Comment by sollhui** [comment]
It seem that metadata can update dynamicly,you can refer nacosDiscoveryProperties,which has get method of metadata and you can use it to update metadata.

**Comment by steverao** [comment]
Spring Cloud don't support the ability that you said above. This is a LoadBalancer problem instead of registry center. In Spring Cloud, If you want to achieve it, you need to do by yourself. By the way, Spring Cloud provides statistical capabilities on the client side instead of the server side, you can see the class of 'com.netflix.loadbalancer.BestAvailableRule' in Ribbon.

**Comment by ruansheng8** [comment]
![image](https://user-images.githubusercontent.com/24709538/178221817-0fab9d38-c782-46b6-adae-a8e28a902936.png)
方案1. 项目中使用的负载均衡规则是NacosRule吗 , Nacos默认实现的负载均衡规则自带权重路由功能 (权重也是带有随机性 , 如果想要永远调用最大权重的那个实例 , 需要继承NacosRule调整权重路由那部分的业务逻辑), 你的管理服务可以根据用户数来更新权重值(用户数越少权重越高 , 需要注意一下权重的取值范围[ 0.0 ,10000.0 ] 用户数过大可以除以一定的倍数 用小数来表示) 

方案2. 参考NacosRule 通过 namingService.selectInstances(name, group, true); 获取到所有实例后 , 调用 instance.getMetadata() 方法获取用户数进行排序 然后返回用户数最低的实例

Nacos相关接口
[修改实例](https://nacos.io/zh-cn/docs/open-api.html#2.3)
[批量更新实例元数据(Beta)](https://nacos.io/zh-cn/docs/open-api.html#2.18)
Nacos Open API : https://nacos.io/zh-cn/docs/open-api.html
