### ISSUE TITLE
Nacos无法注册到public空间

### ISSUE THREAD

**Issue by chenyao99** [alibaba/spring-cloud-alibaba#3277]
nacos-server版本2.2.0
spring-cloud版本2021.0.5
spring-cloud-alibaba版本2021.0.5.0
spring-boot版本2.6.13
当我使用其它不同于nacos账户，配置服务发现并使用默认的namespace时，这个账号授予了一个public的读写权限和另一个的namespace的读写权限
提示Caused by: com.alibaba.nacos.api.exception.NacosException: authorization failed!

**Comment by chenyao99** [comment]
我尝试使用了一个只开放public读写权限的账号，依旧提示authorization failed!
然后我又尝试使用nacos超级管理员账号，能够成功注册到nacos

**Comment by steverao** [comment]
If the problem is about Nacos server authentication, please create relevant issue to Nacos Community.

**Comment by chenyao99** [comment]
> If the problem is about Nacos server authentication, please create relevant issue to Nacos Community.如果问题是关于Nacos服务器身份验证的，请创建相关问题到Nacos社区。

我尝试降低spring-cloud-alibaba的版本至2021.1问题得到解决，这应该是客户端代码的问题

**Comment by lixianli1987** [comment]
> 我尝试使用了一个只开放public读写权限的账号，依旧提示authorization failed! 然后我又尝试使用nacos超级管理员账号，能够成功注册到nacos

我也遇到这个问题了
springboot版本：2.6.8
nacos-server版本：2.2.3
spring-cloud-alibaba版本：2021.0.4.0，对应的nacos-client版本：2.0.4
使用nacos / nacos 注册时，可以注册
我加了个账号 test / test，权限与nacos一样，始终注册不成功
报错：com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
Caused by: com.alibaba.nacos.api.exception.NacosException: authorization failed!

**Comment by lixianli1987** [comment]
> > If the problem is about Nacos server authentication, please create relevant issue to Nacos Community.如果问题是关于Nacos服务器身份验证的，请创建相关问题到Nacos社区。
> 
> 我尝试降低spring-cloud-alibaba的版本至2021.1问题得到解决，这应该是客户端代码的问题

这是升版本吧
