### ISSUE TITLE
failed to request http://nacos:8848/nacos/v1/ns/instance/beat...

### ISSUE THREAD

**Issue by ptsx0607** [alibaba/spring-cloud-alibaba#3299]
1. development environment：
  nacos version：2.0.0
  spring-cloud-starter-alibaba-nacos-config-server version：2.2.1

2. question：
I use docker-compos to start four microservices. There is no problem with the first startup. After a while, one of the services always reports the error shown in the figure below, but it still exists in the nacos service list. What causes this problem?

![image](https://user-images.githubusercontent.com/24916835/236431351-891c9230-c866-4bc0-b310-cd94894e31a9.png)

**Comment by yuluo-yx** [comment]
Adjust the version configuration by referring to the version description.
https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by steverao** [comment]
Firstly, we recommend you use relevant version of client and server according to [version list](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E) from our community. Then, from information you provided, it's very hard to judge what's the problem. Whether it happens occasionally or always exists, if it happens occasionally, you need to check whether it is caused by the instability of your local network.

**Comment by ptsx0607** [comment]
I replaced the nacos version with the matching nacos1.2.1, it seems to have an effect, and it is still under observation...

**Comment by ptsx0607** [comment]
I replaced the nacos version with the matching nacos1.2.1, but the problem is still not solved. The following is a screenshot of the problem：
![5e89f93e98d94f49770da9453b3262d](https://github.com/alibaba/spring-cloud-alibaba/assets/24916835/acac676c-49d6-4361-8f88-081363a3e4f4)
![d280dcd1ee992166ad09cd11ab36784](https://github.com/alibaba/spring-cloud-alibaba/assets/24916835/453542ef-0080-4a9d-94a4-9ecb0f3c947b)
![588cd95b39a37599d8882e3f0333ce9](https://github.com/alibaba/spring-cloud-alibaba/assets/24916835/abb47415-99eb-4b0f-84cd-ecf5a7c85740)
