### ISSUE TITLE
why project move away from spring cloud incubator?

### ISSUE THREAD

**Issue by lzysuqianqiu** [alibaba/spring-cloud-alibaba#739]

**Comment by liupengpop** [comment]
Same question

**Comment by sofkyle** [comment]
I think the first stable version was determined. Is it time to say congratulations?

**Comment by meme-lau** [comment]
bù huì shì bèi tī le ba？

**Comment by spencergibb** [comment]
The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!

**Comment by xiejiashuai** [comment]
> The project did not get kicked out :-) One of the reasons for the move is so that the Alibaba team is not bottlenecked by the spring team for releases. By moving to their own org, they are administrators of the project and #734 allows Alibaba to perform their own releases using their own maven coordinates. Look for continued cooperation, joint blog posts announcing releases and more!

- Why can netflix still use the package name of org.springframework.cloud.netflix, but alibaba does not.
-  Why spring-cloud-aws still use  the package name of org.springframework.cloud.aws, but alibaba does not.

**Comment by spencergibb** [comment]
Because the spring team maintains them and owns springframework.org

**Comment by fangjian0423** [comment]
official policy announcement: https://spring.io/blog/2019/07/24/simplifying-the-spring-cloud-release-train
