### ISSUE TITLE
gateway 集成 swagger2  使用, swagger 不能正常返回结果

### ISSUE THREAD

**Issue by JesseTiger** [alibaba/spring-cloud-alibaba#895]
参考 <<重新定义 spring cloud实战>>这本书里的 spring cloud gateway 集成 swagger2 ,一个 service , 一个 eureka, 一个 gateway ,可以通过网关路由到服务 的 api 界面. 尝试用 gateway 和 nacos 使用,  swagger ui 提示: Fetch error Not Found http://xxxx:8080/v1.0/test/v2/api-docs , 要修改哪些配置项吗?

Using gateway eureka and swagger2 ,gateway can route to  service swagger.
Try using gateway  nacos and swagger2 ,  can not return the results normally ,how to make it return right result ?

**Comment by echooymxq** [comment]
Since eureka can work well, the mapping url `/v2/api-docs` must no problem, So I think you should check the nacos discovery relate configuration, you can reference [https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example)

**Comment by pigxcloud** [comment]
没有看过这本书 这是我的做的效果 基于 spring cloud alibaba
https://swagger.pig4cloud.com/swagger-ui.html

使用 spring cloud alibaba  和 spring cloud  netifix   没有太大的区别 ，看你这个`v1.0 ` 是什么 断言位应该是 `/test`, 应该下边swagger api 调通就可以了

```
http://xxxx:8080/v1.0/test/v2/api-docs
```

**Comment by fangjian0423** [comment]
👍
